export { compileAnimation };
import { getBlockBenchVersion } from "./blockbench_utils.js";

/**
 * Fix the loop mode to the mod's stringified format
 * @param {*} mode The mode to fix
 * @returns The fixed mode
 */
function fixLoopMode(mode) {
    return { once: "ONCE", hold: "HOLD_ON_LAST", loop: "LOOP" }[mode] || "ONCE";
}

/**
 * Compile the animation to a JSON string
 * @param {*} animation The animation to compile
 * @returns The JSON string
 */
function compileAnimation(animation) {
	const animators = animation.animators;

	/* Create the object that will be serialized to JSON */
	let objectForJson = {
		"_comment": `This file was generated by the Kinetic Importer/Exporter plugin for Blockbench-${getBlockBenchVersion()}`,
		"loop": fixLoopMode(animation.loop),
		"startDelay": animation.startDelay,
		"timelines": [],
		"events": {}
	};

	/* For each animator */
	for (let uuid in animators) {
		const ANIMATOR = animators[uuid];
		const KEYFRAMES = ANIMATOR.keyframes;
		
		/* If it's a bone, it's an animated mesh */
		if(ANIMATOR instanceof BoneAnimator) {
			const HAS_GROUP = ANIMATOR.getGroup() != null;

			/* Get the pivot point of the group, default 0,0,0 if no group */
			const ORIGIN = HAS_GROUP ? {
				x: ANIMATOR.getGroup().origin[0],
				y: ANIMATOR.getGroup().origin[1],
				z: ANIMATOR.getGroup().origin[2]
			} : { x: 0, y: 0, z: 0 };

			let mesh = {
				"objectName": HAS_GROUP ? ANIMATOR.getGroup().name : ANIMATOR.name, // Get the name of the group if it exists, otherwise use the name of the animator
				"pivotPoint": ORIGIN,
				"parent": HAS_GROUP ? ANIMATOR.getGroup().parent.name : null, // Get the name of the parent group if it exists, otherwise null
			};
			
			/* Compile the keyframes */
			const FRAMES = new Map();
			KEYFRAMES.forEach(kf => {
				const TIME = kf.getTimecodeString();

				/* If there's no frame for this time, create an empty one */
				if (!FRAMES.has(TIME))
					FRAMES.set(TIME, { "time": TIME });
				
				/* Then put the keyframe data into the frame */
				const FRAME = FRAMES.get(TIME);
				switch (kf.channel) {
					case "position":
						FRAME.position = {
							x: kf.getArray()[0],
							y: kf.getArray()[1],
							z: kf.getArray()[2]
						}
						break;
					case "rotation":
						FRAME.rotation = {
							x: kf.getArray()[0],
							y: kf.getArray()[1],
							z: kf.getArray()[2]
						}
						break;
					case "scale":
						FRAME.scale = {
							x: kf.getArray()[0],
							y: kf.getArray()[1],
							z: kf.getArray()[2]
						}
						break;
				}
			});

			mesh.frames = Array.from(FRAMES.values()); // Add the frames to the object
			objectForJson.timelines.push(mesh); // Add the object to the timelines
		} else // Otherwise, it's an event
			KEYFRAMES.forEach(kf => {
				const TIME = kf.getTimecodeString();

				/* If there's no event for this time, create an empty array */
				if (!objectForJson.events[TIME])
					objectForJson.events[TIME] = [];

				/* Then put the event data into the array */
				objectForJson.events[TIME].push({ 
					"type": kf.channel,
					"path": kf.data_points[0].effect,
					"locator": kf.data_points[0].locator,
					"volume": 1.0, "pitch": 1.0
				});
			});
	}

	return JSON.stringify(objectForJson, null, '\t'); // Finally, return the JSON string with indentation for better readability
}