export { compileModel };
import { exportSingleFileOrZip, getBlockBenchVersion } from './blockbench_utils.js';
import { roundNumber } from './math.js';
import { isSeatElement } from './seats.js';
import { isCollisionElement } from './collisions.js';

function getMtlFace(obj, index) {
	const tex = obj.faces[Canvas.face_order[index]]?.getTexture();
	return tex ? `usemtl ${typeof tex === 'string' ? 'none' : 'm_' + tex.id}` : false;
}

function getAllGroups(children = Outliner.root) {
	return children.flatMap(obj => obj instanceof Group ? [obj, ...getAllGroups(obj.children)] : []);
}

const CUBE_FACE_NORMALS = { north: [0, 0, -1], east: [1, 0, 0], south: [0, 0, 1], west: [-1, 0, 0], up: [0, 1, 0], down: [0, -1, 0] }
function compileModel(shouldExportModel, shouldExportMTL, shouldExportTextures) {
	const PROJECT_NAME = Project.name.toLowerCase() || 'model';
	const OLD_SCENE_POSITION = new THREE.Vector3().copy(scene.position);
	scene.position.set(0, 0, 0);

	let materials = {};
	let obj_file_content = [
		`# This file was generated by the Kinetic Importer/Exporter plugin for Blockbench-${getBlockBenchVersion()}`,
	];

	if(shouldExportMTL) obj_file_content.push('mtllib ' + PROJECT_NAME + '.mtl'); // Reference the MTL file at the beginning of the OBJ, if we want to export MTL

	/* Check all meshes */
	scene.traverse( function (child) {
		if (child instanceof THREE.Mesh) parseMesh(child, obj_file_content, shouldExportMTL);
	});

	/* Handle groups & loose */
	const GROUPS = getAllGroups();
	const LOOSE_ELEMENTS = Outliner.root.filter(obj => obj instanceof OutlinerElement);
	if (LOOSE_ELEMENTS.length) {
		const GROUP = new Group({ name: 'defaultGroup' });
		GROUP.children.push(...LOOSE_ELEMENTS);
		GROUP.is_catch_bone = true;
		GROUP.createUniqueName();
		GROUPS.unshift(GROUP);
	}
	GROUPS.forEach(g => {
		if (g.type !== 'group') return;
		g.children.forEach(obj => {
			if (obj instanceof Locator || obj instanceof NullObject) {
				const [x, y, z] = obj.position;
				obj_file_content.push(`locator ${obj.name} ${-x} ${y} ${z}`);
			}
		});
	});

	/* Set the scene back to the original */
	scene.position.copy(OLD_SCENE_POSITION); // Set the scene position back to what it was before, just in case
	obj_file_content = obj_file_content.join('\n');
	let filesToExport = [];

	/* Generates the MTL content if needed */
	if(shouldExportMTL) {
		var mtlOutput = '';
		for (const MATERIAL in materials) {
			if (materials.hasOwnProperty(MATERIAL) && materials[MATERIAL]) {
				const TEXTURE = materials[MATERIAL];
				mtlOutput += 'newmtl m_' +MATERIAL+ '\n'
				mtlOutput += `map_Kd ${TEXTURE.name} \n`;
			}
		}
		mtlOutput += 'newmtl none'

		/* Add the file for export */
		filesToExport.push({name: PROJECT_NAME, ext: "mtl", content: mtlOutput});
	}
	
	/* Add the images files */
	if(shouldExportTextures) {
		for (const MATERIAL in materials) {
			const TEXTURE = materials[MATERIAL];
			if (TEXTURE && !TEXTURE.error) {
				const TEXTURE_NAME = TEXTURE.name;
				if (TEXTURE_NAME.substr(-4) !== '.png') TEXTURE_NAME += '.png'; // Ensure the texture name ends with .png

				const IMAGE_PATH = path.split(osfs);
				IMAGE_PATH.splice(-1, 1, TEXTURE_NAME);


				Blockbench.writeFile(IMAGE_PATH.join(osfs), {
					content: TEXTURE.source,
					savetype: 'image'
				})
				filesToExport.push({name: TEXTURE_NAME, ext: "png", content: TEXTURE.source});
			}
		}
	}

	/* Add the Model if needed and export */
	if(shouldExportModel) filesToExport.push({name: PROJECT_NAME, ext: "obj", content: obj_file_content});
	exportSingleFileOrZip(filesToExport);
}

function parseMesh(mesh, output, shouldExportMTL) { // TODO Optimize and rewrite this function, it's really messy and not optimized at all. Maybe even split it into multiple functions for better readability
	if(isSeatElement(mesh) || isCollisionElement(mesh)) return; // Don't export seats or collisions

	let indexVertex = 0;
	let indexVertexUvs = 0;
	let indexNormals = 0;
	const vertex = new THREE.Vector3();
	const normal = new THREE.Vector3();
	const uv = new THREE.Vector2();
	const face = [];

	var nbVertex = 0;
	var nbVertexUvs = 0;
	var nbNormals = 0;

	var geometry = mesh.geometry;
	var element  = OutlinerNode.uuids[mesh.name];
	const normalMatrixWorld = new THREE.Matrix3();

	if (!element) return;
	if (element.export === false) return;

	normalMatrixWorld.getNormalMatrix(mesh.matrixWorld);

	if (element instanceof Cube) {
		if(element.parent != null && element.parent.cube != null && element.parent.cube.count <= 1) output.push(`o ${element.parent.name||'mesh'}`)
		else output.push(`o ${element.name||'mesh'}`) 
		if(element.parent != null && element.parent.cube != null) output.push('pivot ' + roundNumber(element.parent.origin[0]) + " " + roundNumber(element.parent.origin[1]) + " " + roundNumber(element.parent.origin[2]))
		else output.push('pivot ' + roundNumber(element.origin[0]) + " " + roundNumber(element.origin[1]) + " " + roundNumber(element.origin[2]))
		
		function addVertex(x, y, z) {
			vertex.set(x - element.origin[0], y - element.origin[1], z - element.origin[2]);
			vertex.applyMatrix4( mesh.matrixWorld ).divideScalar(16);
			output.push('v ' + vertex.x + ' ' + vertex.y + ' ' + vertex.z);
			nbVertex++;
		}
		addVertex(element.to[0]   + element.inflate, element.to[1] +	element.inflate, element.to[2]  	+ element.inflate);
		addVertex(element.to[0]   + element.inflate, element.to[1] +	element.inflate, element.from[2]  	- element.inflate);
		addVertex(element.to[0]   + element.inflate, element.from[1] -	element.inflate, element.to[2]  	+ element.inflate);
		addVertex(element.to[0]   + element.inflate, element.from[1] -	element.inflate, element.from[2]  	- element.inflate);
		addVertex(element.from[0] - element.inflate, element.to[1] +	element.inflate, element.from[2]  	- element.inflate);
		addVertex(element.from[0] - element.inflate, element.to[1] +	element.inflate, element.to[2]  	+ element.inflate);
		addVertex(element.from[0] - element.inflate, element.from[1] -	element.inflate, element.from[2]  	- element.inflate);
		addVertex(element.from[0] - element.inflate, element.from[1] -	element.inflate, element.to[2]  	+ element.inflate);

		for (let key in element.faces) {
			if (element.faces[key].texture !== null) {
				let face = element.faces[key];
				let uv_outputs = [];
				uv_outputs.push(`vt ${face.uv[0] / Project.texture_width} ${1 - face.uv[1] / Project.texture_height}`);
				uv_outputs.push(`vt ${face.uv[2] / Project.texture_width} ${1 - face.uv[1] / Project.texture_height}`);
				uv_outputs.push(`vt ${face.uv[2] / Project.texture_width} ${1 - face.uv[3] / Project.texture_height}`);
				uv_outputs.push(`vt ${face.uv[0] / Project.texture_width} ${1 - face.uv[3] / Project.texture_height}`);
				var rot = face.rotation || 0;
				while (rot > 0) {
					uv_outputs.splice(0, 0, uv_outputs.pop());
					rot -= 90;
				}
				output.push(...uv_outputs);
				nbVertexUvs += 4;
			}
		}
		for (let key in element.faces) {
			if (element.faces[key].texture !== null) {
				normal.fromArray(CUBE_FACE_NORMALS[key]);
				normal.applyMatrix3( normalMatrixWorld ).normalize();
				output.push('vn ' + normal.x + ' ' + normal.y + ' ' + normal.z );
				nbNormals += 1;
			}
		}

		let mtl;
		let i = 0;
		for (let key in element.faces) {
			if (element.faces[key].texture !== null) {
				let tex = element.faces[key].getTexture()
				if (tex && tex.uuid && !materials[tex.id]) { materials[tex.id] = tex; }

				/* Try to add the use mtl if needed */
				if(shouldExportMTL) {
					let mtl_new = (!tex || typeof tex === 'string') ? 'none' : 'm_' + tex.id;
					if (mtl_new != mtl) {
						mtl = mtl_new;
						output.push('usemtl '+mtl);
					}
				}

				let vertices;
				switch (key) {
					case 'north': vertices = [2, 5, 7, 4]; break;
					case 'east': vertices = [1, 2, 4, 3]; break;
					case 'south': vertices = [6, 1, 3, 8]; break;
					case 'west': vertices = [5, 6, 8, 7]; break;
					case 'up': vertices = [5, 2, 1, 6]; break;
					case 'down': vertices = [8, 3, 4, 7]; break;
				}
				output.push('f '+[
					`${vertices[3] + indexVertex}/${i*4 + 4 + indexVertexUvs}/${i+1+indexNormals}`,
					`${vertices[2] + indexVertex}/${i*4 + 3 + indexVertexUvs}/${i+1+indexNormals}`,
					`${vertices[1] + indexVertex}/${i*4 + 2 + indexVertexUvs}/${i+1+indexNormals}`,
					`${vertices[0] + indexVertex}/${i*4 + 1 + indexVertexUvs}/${i+1+indexNormals}`,
				].join(' '));
				i++;
			}
		}
	} else if (element instanceof Mesh) {
		if(element.parent != null && element.parent.mesh != null && element.parent.mesh.count <= 1) { output.push(`o ${element.parent.name||'mesh'}`) }
		else { output.push(`o ${element.name||'mesh'}`) } 
		if(element.parent != null && element.parent.mesh != null) {output.push('pivot ' + roundNumber(element.parent.origin[0]) + " " + roundNumber(element.parent.origin[1]) + " " + roundNumber(element.parent.origin[2])) }
		else { output.push('pivot ' + roundNumber(element.origin[0]) + " " + roundNumber(element.origin[1]) + " " + roundNumber(element.origin[2])) }
		
		let vertex_keys = [];
		function addVertex(x, y, z) {
			vertex.set(x, y, z);
			vertex.applyMatrix4( mesh.matrixWorld ).divideScalar(16);
			output.push('v ' + roundNumber(vertex.x) + ' ' + roundNumber(vertex.y) + ' ' + roundNumber(vertex.z));
			nbVertex++;
		}
		for (let vkey in element.vertices) {
			addVertex(...element.vertices[vkey]);
			vertex_keys.push(vkey);
		}

		let mtl;
		let i = 0;
		let vertexnormals = [];
		let faces = [];
		for (let key in element.faces) {
			if (element.faces[key].texture !== null && element.faces[key].vertices.length >= 3) {
				let face = element.faces[key];
				let vertices = face.getSortedVertices();
				let tex = element.faces[key].getTexture();

				vertices.forEach(vkey => {
					output.push(`vt ${roundNumber(face.uv[vkey][0] / Project.texture_width)} ${roundNumber(1 - face.uv[vkey][1] / Project.texture_height)}`);
					nbVertexUvs += 1;
				})

				normal.fromArray(face.getNormal(true));
				normal.applyMatrix3( normalMatrixWorld ).normalize();
				vertexnormals.push('vn ' + roundNumber(normal.x) + ' ' + roundNumber(normal.y) + ' ' + roundNumber(normal.z) );
				nbNormals += 1;
				
				/* Try to add the use mtl if needed */
				if(shouldExportMTL) {
					if (tex && tex.uuid && !materials[tex.id]) { materials[tex.id] = tex; }
					let mtl_new = (!tex || typeof tex === 'string') ? 'none' : 'm_' + tex.id;
					if (mtl_new != mtl) {
						mtl = mtl_new;
						faces.push('usemtl '+mtl);
					}
				}
				
				let triplets = [];
				vertices.forEach((vkey, vi) => {
					let triplet = [
						vertex_keys.indexOf(vkey) + 1 + indexVertex,
						nbVertexUvs - vertices.length + vi + 1 + indexVertexUvs,
						i+1+indexNormals,
					]
					triplets.push(triplet.join('/'));
				})
				faces.push('f ' + triplets.join(' '));
				i++;
			}
		}
		output.push(...vertexnormals);
		output.push(...faces);
	} else {
		const vertices = geometry.getAttribute( 'position' );
		const normals = geometry.getAttribute( 'normal' );
		const uvs = geometry.getAttribute( 'uv' );
		const indices = geometry.getIndex();

		output.push('o ' + mesh.name);

		if (mesh.material && mesh.material.name) { output.push('usemtl ' + mesh.material.name); }

		if (vertices !== undefined) {
			for ( let i = 0, l = vertices.count; i < l; i ++, nbVertex ++ ) {
				vertex.x = vertices.getX( i );
				vertex.y = vertices.getY( i );
				vertex.z = vertices.getZ( i );
				vertex.applyMatrix4( mesh.matrixWorld ).divideScalar(16);
				output.push('v ' + vertex.x + ' ' + vertex.y + ' ' + vertex.z);
			}
		}

		if ( uvs !== undefined ) {
			for ( let i = 0, l = uvs.count; i < l; i ++, nbVertexUvs ++ ) {
				uv.x = uvs.getX( i );
				uv.y = uvs.getY( i );
				output.push('vt ' + uv.x + ' ' + uv.y);
			}
		}

		if (normals !== undefined) {
			normalMatrixWorld.getNormalMatrix( mesh.matrixWorld );
			for ( let i = 0, l = normals.count; i < l; i ++, nbNormals ++ ) {
				normal.x = normals.getX( i );
				normal.y = normals.getY( i );
				normal.z = normals.getZ( i );
				normal.applyMatrix3( normalMatrixWorld ).normalize();
				output.push('vn ' + normal.x + ' ' + normal.y + ' ' + normal.z );
			}
		}

		for (let key in element.faces) {
			let tex = element.faces[key].getTexture()
			if (tex && tex.uuid && !materials[tex.id]) { materials[tex.id] = tex }
		}

		if ( indices !== null ) {
			for ( let i = 0, l = indices.count; i < l; i += 3 ) {
				let f_mat = getMtlFace(element, geometry.groups[ Math.floor(i / 6) ].materialIndex)
				if (f_mat) {
					if (i % 2 === 0) { output.push(f_mat) }
					for ( let m = 0; m < 3; m ++ ) {
						const j = indices.getX( i + m ) + 1;
						face[ m ] = indexVertex + j + ( normals || uvs ? '/' + ( uvs ? indexVertexUvs + j : '' ) + ( normals ? '/' + ( indexNormals + j ) : '' ) : '' );
					}
					output.push('f ' + face.join( ' ' ) );
				}
			}
		} else {
			for ( let i = 0, l = vertices.count; i < l; i += 3 ) {
				for ( let m = 0; m < 3; m ++ ) {
					const j = i + m + 1;
					face[ m ] = indexVertex + j + ( normals || uvs ? '/' + ( uvs ? indexVertexUvs + j : '' ) + ( normals ? '/' + ( indexNormals + j ) : '' ) : '' );
				}
				output.push('f ' + face.join( ' ' ) );
			}
		}
	}
	indexVertex += nbVertex;
	indexVertexUvs += nbVertexUvs;
	indexNormals += nbNormals;
};